name: theia
channels:
  - pytorch
  - defaults
dependencies:
  - cpuonly=2.0
  - gunicorn=20.1.0
  - pandas=1.4.3
  - pip=22.3.1
  - python=3.10.9
  - pytorch=1.13.1
  - scikit-learn=1.1.1
  - tqdm=4.64.1
  - pip:
    - flask==2.1.2
    - drfp==0.3.6
    - annoy==1.15.0
    - rdkit-pypi==2022.3.4
    - click==8.1.3
    - shap==0.41.0
    - sentry-sdk[flask]
    - intel_extension_for_pytorch
